version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 200m
  elastic:
  docker.elastic.co/elasticsearch/elasticsearch:7.17.0
  collector:
    image: "elastic-sandbox"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 500m
    environment:
      - FALLBACK_ENABLED=false


