version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 200m
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    deploy:
      resources:
        limits:
          memory: 700m

  collector:
    image: "elastic-sandbox"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 500m
    environment:
      - FALLBACK_ENABLED=false


